<a href="https://colab.research.google.com/github/suarezthura1/Githubtesting/blob/main/Thomas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [1]:
import pandas as pd
import numpy as np

Importing Dataset

In [2]:
dataset = pd.read_csv('/content/Coffee_Dataset.csv')
x = dataset.iloc[:,[0,2]].values
y = dataset.iloc[:,[3]].values


In [3]:
print(x)

[[1 'AA']
 [2 'AB']
 [3 'C']
 [4 'AA']
 [5 'AB']
 [6 'C']
 [7 'AA']
 [8 'AB']
 [9 'C']
 [10 'AA']
 [11 'AB']
 [12 'C']
 [13 'AA']
 [14 'AB']
 [15 'C']
 [16 'AA']
 [17 'AB']
 [18 'C']
 [19 'AA']
 [20 'AB']
 [21 'C']
 [22 'AA']
 [23 'AB']
 [24 'C']
 [25 'AA']
 [26 'AB']
 [27 'C']
 [28 'AA']
 [29 'AB']
 [30 'C']
 [31 'AA']
 [32 'AB']
 [33 'C']
 [34 'AA']
 [35 'AB']
 [36 'C']
 [37 'AA']
 [38 'AB']
 [39 'C']
 [40 'AA']
 [41 'AB']
 [42 'C']
 [43 'AA']
 [44 'AB']
 [45 'C']
 [46 'AA']
 [47 'AB']
 [48 'C']
 [49 'AA']
 [50 'AB']
 [51 'C']
 [52 'AA']
 [53 'AB']
 [54 'C']
 [55 'AA']
 [56 'AB']
 [57 'C']
 [58 'AA']
 [59 'AB']
 [60 'C']
 [61 'AA']
 [62 'AB']
 [63 'C']
 [64 'AA']
 [65 'AB']
 [66 'C']
 [67 'AA']
 [68 'AB']
 [69 'C']
 [70 'AA']
 [71 'AB']
 [72 'C']
 [73 'AA']
 [74 'AB']
 [75 'C']
 [76 'AA']
 [77 'AB']
 [78 'C']
 [79 'AA']
 [80 'AB']
 [81 'C']
 [82 'AA']
 [83 'AB']
 [84 'C']
 [85 'AA']
 [86 'AB']
 [87 'C']
 [88 'AA']
 [89 'AB']
 [90 'C']
 [91 'AA']
 [92 'AB']
 [93 'C']
 [94 'AA']
 [95 '

In [4]:
print(y)

[[236.98]
 [211.06]
 [168.1 ]
 [267.01]
 [231.54]
 [163.36]
 [300.68]
 [258.07]
 [173.72]
 [297.77]
 [239.33]
 [174.23]
 [297.31]
 [245.34]
 [187.46]
 [265.87]
 [235.08]
 [188.68]
 [221.91]
 [207.64]
 [169.92]
 [217.81]
 [199.66]
 [165.07]
 [222.2 ]
 [191.35]
 [171.74]
 [206.8 ]
 [220.83]
 [178.87]
 [253.72]
 [233.58]
 [205.41]
 [255.69]
 [239.29]
 [207.07]
 [340.38]
 [263.44]
 [188.55]
 [371.49]
 [239.48]
 [184.85]
 [360.45]
 [233.76]
 [179.57]
 [365.23]
 [266.09]
 [191.25]
 [384.3 ]
 [296.22]
 [219.51]
 [330.06]
 [252.92]
 [186.72]
 [275.27]
 [202.54]
 [142.69]
 [234.95]
 [172.52]
 [121.03]
 [308.66]
 [213.82]
 [159.48]
 [317.01]
 [206.81]
 [145.51]
 [309.1 ]
 [195.03]
 [123.65]
 [291.27]
 [234.8 ]
 [206.07]
 [335.9 ]
 [262.7 ]
 [208.61]
 [269.05]
 [222.1 ]
 [187.64]
 [238.38]
 [207.16]
 [178.59]
 [229.27]
 [204.57]
 [167.06]
 [220.2 ]
 [198.82]
 [171.3 ]
 [229.18]
 [210.5 ]
 [178.17]
 [228.21]
 [214.25]
 [171.78]
 [310.71]
 [254.42]
 [232.12]
 [300.48]
 [251.45]
 [230.38]
 [295.75]


Data Preprocessing

In [5]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])

In [6]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = ct.fit_transform(x)

In [7]:
print(x)

[[1.0 0.0 0.0 1]
 [0.0 1.0 0.0 2]
 [0.0 0.0 1.0 3]
 [1.0 0.0 0.0 4]
 [0.0 1.0 0.0 5]
 [0.0 0.0 1.0 6]
 [1.0 0.0 0.0 7]
 [0.0 1.0 0.0 8]
 [0.0 0.0 1.0 9]
 [1.0 0.0 0.0 10]
 [0.0 1.0 0.0 11]
 [0.0 0.0 1.0 12]
 [1.0 0.0 0.0 13]
 [0.0 1.0 0.0 14]
 [0.0 0.0 1.0 15]
 [1.0 0.0 0.0 16]
 [0.0 1.0 0.0 17]
 [0.0 0.0 1.0 18]
 [1.0 0.0 0.0 19]
 [0.0 1.0 0.0 20]
 [0.0 0.0 1.0 21]
 [1.0 0.0 0.0 22]
 [0.0 1.0 0.0 23]
 [0.0 0.0 1.0 24]
 [1.0 0.0 0.0 25]
 [0.0 1.0 0.0 26]
 [0.0 0.0 1.0 27]
 [1.0 0.0 0.0 28]
 [0.0 1.0 0.0 29]
 [0.0 0.0 1.0 30]
 [1.0 0.0 0.0 31]
 [0.0 1.0 0.0 32]
 [0.0 0.0 1.0 33]
 [1.0 0.0 0.0 34]
 [0.0 1.0 0.0 35]
 [0.0 0.0 1.0 36]
 [1.0 0.0 0.0 37]
 [0.0 1.0 0.0 38]
 [0.0 0.0 1.0 39]
 [1.0 0.0 0.0 40]
 [0.0 1.0 0.0 41]
 [0.0 0.0 1.0 42]
 [1.0 0.0 0.0 43]
 [0.0 1.0 0.0 44]
 [0.0 0.0 1.0 45]
 [1.0 0.0 0.0 46]
 [0.0 1.0 0.0 47]
 [0.0 0.0 1.0 48]
 [1.0 0.0 0.0 49]
 [0.0 1.0 0.0 50]
 [0.0 0.0 1.0 51]
 [1.0 0.0 0.0 52]
 [0.0 1.0 0.0 53]
 [0.0 0.0 1.0 54]
 [1.0 0.0 0.0 55]
 [0.0 1.0 0.0 56]
 

Feature scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [9]:
print(x)

[[ 1.41421356 -0.70710678 -0.70710678 -1.72319115]
 [-0.70710678  1.41421356 -0.70710678 -1.7054263 ]
 [-0.70710678 -0.70710678  1.41421356 -1.68766144]
 [ 1.41421356 -0.70710678 -0.70710678 -1.66989658]
 [-0.70710678  1.41421356 -0.70710678 -1.65213173]
 [-0.70710678 -0.70710678  1.41421356 -1.63436687]
 [ 1.41421356 -0.70710678 -0.70710678 -1.61660201]
 [-0.70710678  1.41421356 -0.70710678 -1.59883715]
 [-0.70710678 -0.70710678  1.41421356 -1.5810723 ]
 [ 1.41421356 -0.70710678 -0.70710678 -1.56330744]
 [-0.70710678  1.41421356 -0.70710678 -1.54554258]
 [-0.70710678 -0.70710678  1.41421356 -1.52777772]
 [ 1.41421356 -0.70710678 -0.70710678 -1.51001287]
 [-0.70710678  1.41421356 -0.70710678 -1.49224801]
 [-0.70710678 -0.70710678  1.41421356 -1.47448315]
 [ 1.41421356 -0.70710678 -0.70710678 -1.4567183 ]
 [-0.70710678  1.41421356 -0.70710678 -1.43895344]
 [-0.70710678 -0.70710678  1.41421356 -1.42118858]
 [ 1.41421356 -0.70710678 -0.70710678 -1.40342372]
 [-0.70710678  1.41421356 -0.70

Splitting Dataset into Training and Testing

In [10]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size=0.1,random_state=0)

Training Model

In [11]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [12]:
y_pred = regression.predict(x_test)

In [13]:
print(y_pred)

[175.5346 289.3721 279.7533 217.8016 321.446  226.1309 212.402  264.1122
 197.3084 229.5965 233.2331 171.0602 228.4064 202.65   226.095  241.624
 318.7777 290.4148 189.3495 253.802 ]


In [14]:
print(y_test)

[[167.06]
 [297.31]
 [255.69]
 [157.29]
 [314.4 ]
 [174.2 ]
 [229.4 ]
 [251.54]
 [208.61]
 [221.91]
 [258.07]
 [163.36]
 [216.86]
 [145.8 ]
 [224.7 ]
 [251.6 ]
 [279.11]
 [308.66]
 [179.57]
 [221.9 ]]


Testing Result

In [15]:
mydata = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

Calculating Accuracy

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6991683237904716

Making Dataframe

In [17]:
Dataframe = (pd.DataFrame(mydata,columns=['predicted value','Real value']))

In [18]:
print(Dataframe)

    predicted value  Real value
0          175.5346      167.06
1          289.3721      297.31
2          279.7533      255.69
3          217.8016      157.29
4          321.4460      314.40
5          226.1309      174.20
6          212.4020      229.40
7          264.1122      251.54
8          197.3084      208.61
9          229.5965      221.91
10         233.2331      258.07
11         171.0602      163.36
12         228.4064      216.86
13         202.6500      145.80
14         226.0950      224.70
15         241.6240      251.60
16         318.7777      279.11
17         290.4148      308.66
18         189.3495      179.57
19         253.8020      221.90
