<a href="https://colab.research.google.com/github/suarezthura1/Githubtesting/blob/main/Thomas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [148]:
import pandas as pd
import numpy as np

Importing Dataset

In [149]:
dataset = pd.read_csv('/content/monthly_coffee_prices.csv')
x = dataset.iloc[:,[0,2]].values
y = dataset.iloc[:,[3]].values


In [150]:
print(x)

[[1 'AA']
 [2 'AB']
 [3 'C']
 [17 'AA']
 [18 'AB']
 [19 'C']
 [34 'AA']
 [35 'AB']
 [36 'C']
 [53 'AA']
 [54 'AB']
 [55 'C']
 [70 'AA']
 [71 'AB']
 [72 'C']
 [87 'AA']
 [88 'AB']
 [89 'C']
 [106 'AA']
 [107 'AB']
 [108 'C']
 [123 'AA']
 [124 'AB']
 [125 'C']
 [140 'AA']
 [141 'AB']
 [142 'C']
 [159 'AA']
 [160 'AB']
 [161 'C']
 [176 'AA']
 [177 'AB']
 [178 'C']
 [192 'AA']
 [193 'AB']
 [194 'C']
 [1 'AA']
 [2 'AB']
 [3 'C']
 [18 'AA']
 [19 'AB']
 [20 'C']
 [35 'AA']
 [36 'AB']
 [37 'C']
 [54 'AA']
 [55 'AB']
 [56 'C']
 [71 'AA']
 [72 'AB']
 [73 'C']
 [87 'AA']
 [88 'AB']
 [89 'C']
 [105 'AA']
 [106 'AB']
 [107 'C']
 [122 'AA']
 [123 'AB']
 [124 'C']
 [139 'AA']
 [140 'AB']
 [141 'C']
 [158 'AA']
 [159 'AB']
 [160 'C']
 [175 'AA']
 [176 'AB']
 [177 'C']
 [8 'AA']
 [9 'AB']
 [10 'C']
 [24 'AA']
 [25 'AB']
 [26 'C']
 [40 'AA']
 [41 'AB']
 [42 'C']
 [7 'AA']
 [8 'AB']
 [9 'C']
 [24 'AA']
 [25 'AB']
 [26 'C']
 [41 'AA']
 [42 'AB']
 [43 'C']
 [7 'AA']
 [8 'AB']
 [9 'C']
 [23 'AA']
 [24 'AB']

In [151]:
print(y)

[[236.98]
 [211.06]
 [168.1 ]
 [267.01]
 [231.54]
 [163.36]
 [300.68]
 [258.07]
 [173.72]
 [297.77]
 [239.33]
 [174.23]
 [297.31]
 [245.34]
 [187.46]
 [265.87]
 [235.08]
 [188.68]
 [221.91]
 [207.64]
 [169.92]
 [217.81]
 [199.66]
 [165.07]
 [222.2 ]
 [191.35]
 [171.74]
 [206.8 ]
 [220.83]
 [178.87]
 [253.72]
 [233.58]
 [205.41]
 [255.69]
 [239.29]
 [207.07]
 [340.38]
 [263.44]
 [188.55]
 [371.49]
 [239.48]
 [184.85]
 [360.45]
 [233.76]
 [179.57]
 [365.23]
 [266.09]
 [191.25]
 [384.3 ]
 [296.22]
 [219.51]
 [330.06]
 [252.92]
 [186.72]
 [275.27]
 [202.54]
 [142.69]
 [234.95]
 [172.52]
 [121.03]
 [308.66]
 [213.82]
 [159.48]
 [317.01]
 [206.81]
 [145.51]
 [309.1 ]
 [195.03]
 [123.65]
 [291.27]
 [234.8 ]
 [206.07]
 [335.9 ]
 [262.7 ]
 [208.61]
 [269.05]
 [222.1 ]
 [187.64]
 [238.38]
 [207.16]
 [178.59]
 [229.27]
 [204.57]
 [167.06]
 [220.2 ]
 [198.82]
 [171.3 ]
 [229.18]
 [210.5 ]
 [178.17]
 [228.21]
 [214.25]
 [171.78]
 [310.71]
 [254.42]
 [232.12]
 [300.48]
 [251.45]
 [230.38]
 [295.75]


Data Preprocessing

In [152]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])

In [153]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = ct.fit_transform(x)

In [154]:
print(x)

[[1.0 0.0 0.0 1]
 [0.0 1.0 0.0 2]
 [0.0 0.0 1.0 3]
 [1.0 0.0 0.0 17]
 [0.0 1.0 0.0 18]
 [0.0 0.0 1.0 19]
 [1.0 0.0 0.0 34]
 [0.0 1.0 0.0 35]
 [0.0 0.0 1.0 36]
 [1.0 0.0 0.0 53]
 [0.0 1.0 0.0 54]
 [0.0 0.0 1.0 55]
 [1.0 0.0 0.0 70]
 [0.0 1.0 0.0 71]
 [0.0 0.0 1.0 72]
 [1.0 0.0 0.0 87]
 [0.0 1.0 0.0 88]
 [0.0 0.0 1.0 89]
 [1.0 0.0 0.0 106]
 [0.0 1.0 0.0 107]
 [0.0 0.0 1.0 108]
 [1.0 0.0 0.0 123]
 [0.0 1.0 0.0 124]
 [0.0 0.0 1.0 125]
 [1.0 0.0 0.0 140]
 [0.0 1.0 0.0 141]
 [0.0 0.0 1.0 142]
 [1.0 0.0 0.0 159]
 [0.0 1.0 0.0 160]
 [0.0 0.0 1.0 161]
 [1.0 0.0 0.0 176]
 [0.0 1.0 0.0 177]
 [0.0 0.0 1.0 178]
 [1.0 0.0 0.0 192]
 [0.0 1.0 0.0 193]
 [0.0 0.0 1.0 194]
 [1.0 0.0 0.0 1]
 [0.0 1.0 0.0 2]
 [0.0 0.0 1.0 3]
 [1.0 0.0 0.0 18]
 [0.0 1.0 0.0 19]
 [0.0 0.0 1.0 20]
 [1.0 0.0 0.0 35]
 [0.0 1.0 0.0 36]
 [0.0 0.0 1.0 37]
 [1.0 0.0 0.0 54]
 [0.0 1.0 0.0 55]
 [0.0 0.0 1.0 56]
 [1.0 0.0 0.0 71]
 [0.0 1.0 0.0 72]
 [0.0 0.0 1.0 73]
 [1.0 0.0 0.0 87]
 [0.0 1.0 0.0 88]
 [0.0 0.0 1.0 89]
 [1.0 0.0 0.0 10

Feature scaling

In [158]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [159]:
print(x)

[[ 1.41421356 -0.70710678 -0.70710678 -1.04067816]
 [-0.70710678  1.41421356 -0.70710678 -1.02279849]
 [-0.70710678 -0.70710678  1.41421356 -1.00491882]
 [ 1.41421356 -0.70710678 -0.70710678 -0.75460342]
 [-0.70710678  1.41421356 -0.70710678 -0.73672375]
 [-0.70710678 -0.70710678  1.41421356 -0.71884407]
 [ 1.41421356 -0.70710678 -0.70710678 -0.450649  ]
 [-0.70710678  1.41421356 -0.70710678 -0.43276933]
 [-0.70710678 -0.70710678  1.41421356 -0.41488965]
 [ 1.41421356 -0.70710678 -0.70710678 -0.11093524]
 [-0.70710678  1.41421356 -0.70710678 -0.09305556]
 [-0.70710678 -0.70710678  1.41421356 -0.07517589]
 [ 1.41421356 -0.70710678 -0.70710678  0.19301918]
 [-0.70710678  1.41421356 -0.70710678  0.21089885]
 [-0.70710678 -0.70710678  1.41421356  0.22877853]
 [ 1.41421356 -0.70710678 -0.70710678  0.4969736 ]
 [-0.70710678  1.41421356 -0.70710678  0.51485327]
 [-0.70710678 -0.70710678  1.41421356  0.53273295]
 [ 1.41421356 -0.70710678 -0.70710678  0.83668736]
 [-0.70710678  1.41421356 -0.70

Splitting Dataset into Training and Testing

In [161]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size=0.1,random_state=0)

Training Model

In [163]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [164]:
y_pred = regression.predict(x_test)

In [165]:
print(y_pred)

[289.89034167 227.824      158.0149     232.7726     245.3143
 286.642575   261.7977     262.2274     232.7726     232.7726
 301.01994    161.5863     260.5592     313.3515    ]


In [166]:
print(y_test)

[[310.71]
 [309.1 ]
 [171.74]
 [173.72]
 [253.72]
 [214.25]
 [276.39]
 [242.69]
 [179.57]
 [224.97]
 [295.75]
 [142.69]
 [233.76]
 [300.48]]


Testing Result

In [169]:
mydata = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

Calculating Accuracy

In [168]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.4943249696727404

Making Dataframe

In [175]:
Dataframe = (pd.DataFrame(mydata,columns=['predicted value','Real value']))

In [177]:
print(Dataframe)

    predicted value  Real value
0        289.890342      310.71
1        227.824000      309.10
2        158.014900      171.74
3        232.772600      173.72
4        245.314300      253.72
5        286.642575      214.25
6        261.797700      276.39
7        262.227400      242.69
8        232.772600      179.57
9        232.772600      224.97
10       301.019940      295.75
11       161.586300      142.69
12       260.559200      233.76
13       313.351500      300.48
