<a href="https://colab.research.google.com/github/suarezthura1/Githubtesting/blob/main/Thomas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries

In [108]:
import pandas as pd
import numpy as np

Importing Dataset

In [109]:
dataset = pd.read_csv('/content/Coffee_Dataset.csv')
x = dataset.iloc[:,[0,2]].values
y = dataset.iloc[:,[3]].values


In [110]:
print(x)

[[1 'AA']
 [2 'AB']
 [3 'C']
 [4 'AA']
 [5 'AB']
 [6 'C']
 [7 'AA']
 [8 'AB']
 [9 'C']
 [10 'AA']
 [11 'AB']
 [12 'C']
 [13 'AA']
 [14 'AB']
 [15 'C']
 [16 'AA']
 [17 'AB']
 [18 'C']
 [19 'AA']
 [20 'AB']
 [21 'C']
 [22 'AA']
 [23 'AB']
 [24 'C']
 [25 'AA']
 [26 'AB']
 [27 'C']
 [28 'AA']
 [29 'AB']
 [30 'C']
 [31 'AA']
 [32 'AB']
 [33 'C']
 [34 'AA']
 [35 'AB']
 [36 'C']
 [37 'AA']
 [38 'AB']
 [39 'C']
 [40 'AA']
 [41 'AB']
 [42 'C']
 [43 'AA']
 [44 'AB']
 [45 'C']
 [46 'AA']
 [47 'AB']
 [48 'C']
 [49 'AA']
 [50 'AB']
 [51 'C']
 [52 'AA']
 [53 'AB']
 [54 'C']
 [55 'AA']
 [56 'AB']
 [57 'C']
 [58 'AA']
 [59 'AB']
 [60 'C']
 [61 'AA']
 [62 'AB']
 [63 'C']
 [64 'AA']
 [65 'AB']
 [66 'C']
 [67 'AA']
 [68 'AB']
 [69 'C']
 [70 'AA']
 [71 'AB']
 [72 'C']
 [73 'AA']
 [74 'AB']
 [75 'C']
 [76 'AA']
 [77 'AB']
 [78 'C']
 [79 'AA']
 [80 'AB']
 [81 'C']
 [82 'AA']
 [83 'AB']
 [84 'C']
 [85 'AA']
 [86 'AB']
 [87 'C']
 [88 'AA']
 [89 'AB']
 [90 'C']
 [91 'AA']
 [92 'AB']
 [93 'C']
 [94 'AA']
 [95 '

In [111]:
print(y)

[[236.98]
 [211.06]
 [168.1 ]
 [267.01]
 [231.54]
 [163.36]
 [300.68]
 [258.07]
 [173.72]
 [297.77]
 [239.33]
 [174.23]
 [297.31]
 [245.34]
 [187.46]
 [265.87]
 [235.08]
 [188.68]
 [221.91]
 [207.64]
 [169.92]
 [217.81]
 [199.66]
 [165.07]
 [222.2 ]
 [191.35]
 [171.74]
 [206.8 ]
 [220.83]
 [178.87]
 [253.72]
 [233.58]
 [205.41]
 [255.69]
 [239.29]
 [207.07]
 [340.38]
 [263.44]
 [188.55]
 [371.49]
 [239.48]
 [184.85]
 [360.45]
 [233.76]
 [179.57]
 [365.23]
 [266.09]
 [191.25]
 [384.3 ]
 [296.22]
 [219.51]
 [330.06]
 [252.92]
 [186.72]
 [275.27]
 [202.54]
 [142.69]
 [234.95]
 [172.52]
 [121.03]
 [308.66]
 [213.82]
 [159.48]
 [317.01]
 [206.81]
 [145.51]
 [309.1 ]
 [195.03]
 [123.65]
 [291.27]
 [234.8 ]
 [206.07]
 [335.9 ]
 [262.7 ]
 [208.61]
 [269.05]
 [222.1 ]
 [187.64]
 [238.38]
 [207.16]
 [178.59]
 [229.27]
 [204.57]
 [167.06]
 [220.2 ]
 [198.82]
 [171.3 ]
 [229.18]
 [210.5 ]
 [178.17]
 [228.21]
 [214.25]
 [171.78]
 [310.71]
 [254.42]
 [232.12]
 [300.48]
 [251.45]
 [230.38]
 [295.75]


Data Preprocessing

In [112]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x[:,1] = le1.fit_transform(x[:,1])

In [113]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = ct.fit_transform(x)

In [114]:
print(x)

[[1.0 0.0 0.0 1]
 [0.0 1.0 0.0 2]
 [0.0 0.0 1.0 3]
 ...
 [1.0 0.0 0.0 301]
 [0.0 1.0 0.0 302]
 [0.0 0.0 1.0 303]]


Feature scaling

In [115]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [116]:
print(x)

[[ 1.41421356 -0.70710678 -0.70710678 -1.72590998]
 [-0.70710678  1.41421356 -0.70710678 -1.71448261]
 [-0.70710678 -0.70710678  1.41421356 -1.70305524]
 ...
 [ 1.41421356 -0.70710678 -0.70710678  1.70230095]
 [-0.70710678  1.41421356 -0.70710678  1.71372832]
 [-0.70710678 -0.70710678  1.41421356  1.72515569]]


Splitting Dataset into Training and Testing

In [117]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test) = train_test_split(x,y,test_size=0.05,random_state=0)

Training Model

In [118]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [119]:
y_pred = regression.predict(x_test)

In [120]:
print(y_pred)

[242.6627 181.685  240.9807 284.855  269.5437 183.5869 249.025  346.678
 167.899  167.534  331.4719 271.8584 137.198  289.0457 228.626  307.237 ]


In [121]:
print(y_test)

[[258.3 ]
 [178.9 ]
 [265.3 ]
 [309.6 ]
 [252.92]
 [187.46]
 [245.3 ]
 [323.2 ]
 [154.1 ]
 [174.5 ]
 [272.64]
 [297.3 ]
 [148.7 ]
 [297.31]
 [265.87]
 [309.1 ]]


Testing Result

In [122]:
mydata = np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1)

Calculating Accuracy

In [123]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8409610825312426

Making Dataframe

In [124]:
Dataframe = (pd.DataFrame(mydata,columns=['predicted value','Real value']))

In [126]:
print(Dataframe)

    predicted value  Real value
0          242.6627      258.30
1          181.6850      178.90
2          240.9807      265.30
3          284.8550      309.60
4          269.5437      252.92
5          183.5869      187.46
6          249.0250      245.30
7          346.6780      323.20
8          167.8990      154.10
9          167.5340      174.50
10         331.4719      272.64
11         271.8584      297.30
12         137.1980      148.70
13         289.0457      297.31
14         228.6260      265.87
15         307.2370      309.10


Model Visualization

In [127]:
import matplotlib.pyplot as plt
%matplotlib inline

In [128]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(random_state=0)
dataset = ('/content/Coffee_Dataset.csv')

In [129]:
import seaborn as sns

In [130]:
len(x) == len(y)

True

In [131]:
rfc = RandomForestRegressor
rfc.feature_importances_